import type { ComponentType, CSSProperties } from 'react';
import { Dices, Eye, Sigma } from 'lucide-react';
import { FaJava } from 'react-icons/fa';
import {
  SiAmazons3,
  SiAmazonwebservices,
  SiAngular,
  SiAnthropic,
  SiC,
  SiCplusplus,
  SiDocker,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGnubash,
  SiGo,
  SiGooglecloud,
  SiGooglegemini,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJira,
  SiKotlin,
  SiLinux,
  SiMongodb,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiReact,
  SiSpringboot,
  SiTypescript,
} from 'react-icons/si';

export type TechIcon = { icon: ComponentType<{ className?: string; style?: CSSProperties }>; color: string };

/** Brand icon + color for each technology name used on the site. */
export const TECH_ICONS: Record<string, TechIcon> = {
  Python: { icon: SiPython, color: '#4B8BBE' },
  Java: { icon: FaJava, color: '#E76F00' },
  C: { icon: SiC, color: '#A8B9CC' },
  'C++': { icon: SiCplusplus, color: '#659AD2' },
  TypeScript: { icon: SiTypescript, color: '#3178C6' },
  JavaScript: { icon: SiJavascript, color: '#F7DF1E' },
  Go: { icon: SiGo, color: '#00ADD8' },
  Kotlin: { icon: SiKotlin, color: '#7F52FF' },
  Shell: { icon: SiGnubash, color: '#4EAA25' },
  'HTML/CSS': { icon: SiHtml5, color: '#E34F26' },
  React: { icon: SiReact, color: '#61DAFB' },
  'Next.js': { icon: SiNextdotjs, color: '#FFFFFF' },
  'Node.js': { icon: SiNodedotjs, color: '#5FA04E' },
  Angular: { icon: SiAngular, color: '#DD0031' },
  FastAPI: { icon: SiFastapi, color: '#009688' },
  Flask: { icon: SiFlask, color: '#FFFFFF' },
  'Spring Boot': { icon: SiSpringboot, color: '#6DB33F' },
  PostgreSQL: { icon: SiPostgresql, color: '#4169E1' },
  MongoDB: { icon: SiMongodb, color: '#47A248' },
  Docker: { icon: SiDocker, color: '#2496ED' },
  AWS: { icon: SiAmazonwebservices, color: '#FF9900' },
  'AWS S3': { icon: SiAmazons3, color: '#569A31' },
  'Google Cloud Platform': { icon: SiGooglecloud, color: '#4285F4' },
  Jenkins: { icon: SiJenkins, color: '#D24939' },
  Nginx: { icon: SiNginx, color: '#009639' },
  Git: { icon: SiGit, color: '#F05032' },
  Linux: { icon: SiLinux, color: '#FCC624' },
  Jira: { icon: SiJira, color: '#2684FF' },
  'Gemini API': { icon: SiGooglegemini, color: '#8E75B2' },
  'Anthropic API': { icon: SiAnthropic, color: '#D4A27F' },
  'Computer Vision': { icon: Eye, color: '#7DD3FC' },
  'Kalman Filtering': { icon: Sigma, color: '#FBBF24' },
  'Monte Carlo': { icon: Dices, color: '#F472B6' },
};
